spring.application.name=distribuidora

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG

# Docker
spring.docker.compose.enabled=false
